from gym.envs.registration import register
register(id = "net-v0", entry_point = "net_env.envs:NetEnv",)
register(id = "net-v1", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 4, "id":"s1"})
register(id = "net-v2", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 4, "id":"s2"})
register(id = "net-v3", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 4, "id":"s3"})
register(id = "net-v4", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 4, "id":"s4"})
register(id = "net-v5", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 5, "id":"l1"})
register(id = "net-v6", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 5, "id":"l2"})
register(id = "net-v7", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 5, "id":"l3"})
register(id = "net-v8", entry_point = "net_env.envs:NetEnv", kwargs = {'nports' : 5, "id":"l4"})
